name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: install
        run: |
          yarn install
      - name: start
        run: |
          yarn webapp:start:api &
      - name: tests
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3001/'
          responseCode: 200
          timeout: 120000
          interval: 2000
        run: |
          yarn playwright-e2e:test:api
